import "materialize-css/dist/css/materialize.min.css"
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Navbar from '../components/navbar.js'
import Footer from '../components/footer.js'
import BG_logo from '../img/worldseed_thumbnail.jpeg'
import Elden_img from '../img/elden_ring.jpg'
import Image from 'next/image'
import Link from 'next/link'


export default function Game() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Fireball</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar/>

      <main className={styles.main}>
        <div className="gameinfo-container white-text">
              <div className="row">
              <h1>Elden Ring</h1>
                  <div className="col right-part s12 m12 l8">
                    <Image src={BG_logo} />
                      <h2>LORfozihfoazuhgoua haziuo heuigh aeoug haziufg aeuifg azuofh azipuofh azuiofh</h2>
                      <p>Type</p>
                      Action
                      <p>ozaj îaehgoiahg poiaegh eugh ez ugh oegh oizagh oizaigh zaoigh izofh oazigh oizigh oazgh azogh ozagh azio ghoazigh oziagh aozigh aziogh ozaigh oaizg hoazig hzaiog hozi hazoig haziogh oazig haziog hazoig hazoi gh</p>
                  </div>
                  <div className="col left-part s12 m12 l4">
                      <div className="center-align">
                        <Image className="left-img" src={Elden_img} width={220} height={300} />
                      </div>
                      
                      <div className="container">
                          <p>59.99$</p>
                          <div><a className="purchase waves-effect waves-light btn-large">PURCHASE</a></div>
                          <div><a className="add-basket waves-effect waves-light btn-large">ADD TO BASKET</a></div>
                          <div className="row">
                              <div className="col border s12 m12 l12">
                                  <div className="col left s6 m6 l6"><p>Developper</p></div>
                                  <div className="col right s6 m6 l6"><p>From Software</p></div>
                              </div>
                              <div className="col border s12 m12 l12">
                                  <div className="col left s6 m6 l6"><p>Editor</p></div>
                                  <div className="col right s6 m6 l6"><p>From Software</p></div>
                              </div>
                              <div className="col border s12 m12 l12">
                                  <div className="col left s6 m6 l6"><p>Release date</p></div>
                                  <div className="col right s6 m6 l6"><p>25/02/2022</p></div>
                              </div>
                              <div className="col border s12 m12 l12">
                                  <div className="col left s6 m6 l6"><p>Platform</p></div>
                                  <div className="col right s6 m6 l6"><p>PC/PS/XBOX</p></div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </main>

      <Footer/>
    </div>
  )
}
