import "materialize-css/dist/css/materialize.min.css"
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Navbar from '../components/navbar.js'
import Footer from '../components/footer.js'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Fireball</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar/>

      <main className={styles.main}>
      
      </main>

      <Footer/>
    </div>
  )
}
